//Celebrity Problem : https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbm11U0ZHU3N6d0pOakgyVHZvNU1JOF9jMWFZUXxBQ3Jtc0tsek9kTENNQU1tU0hrT0VESHZPWWZJQmZ6bFpzNmVrckNBc2VfOXZaZ0Z1OFRDWnlCQWlxQ2FyYUlRUzVnX0VfLW9RcENwZlZiVmpyV3pVT3hyaDFfRUlYQThYUXFxaERVZzE1MXlBSDQyUk53S19wSQ&q=https%3A%2F%2Fpractice.geeksforgeeks.org%2Fproblems%2Fthe-celebrity-problem%2F1%2F&v=9u2BJfmWNEg


