//Balanced Tree or Not : https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa1VQbnBBUURHYTFoNGhHdm91ZDBVcE5Cc2JjQXxBQ3Jtc0trdzZsM094VWc5WnZqZ0xtZ2p5eDVEd1BXWktsdlRQcGFkeGtGbUhaR2tQOU5BZFJ3SFdVeF95Qng4azhOaHk2ZzJxdXROTHVmV0NmMnhJczdxaENqVDhibTJTZEJwQWZDQW16U015WjFHNHBJbm0yRQ&q=https%3A%2F%2Fpractice.geeksforgeeks.org%2Fproblems%2Fcheck-for-balanced-tree%2F1&v=nHMQ33LZ6oA


