//Sum Tree or Not : https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbk1JcENFS181UnQ2SjRJam9lVXRrcjlpbVNqZ3xBQ3Jtc0tucGp3Rkp5ZkRRMXZDb0RGb0hUUFUybzFVS1BtTjZxTlNsdDJfM2NwbWFKNUp2amFIbjFXQXJZNkJwbE5Fb09wTkJaRGpsVHF3eHlEUEx5SnYtdVctQldUcjZmOURfMURmVlhjZWtSSEhuM3luTDdKVQ&q=https%3A%2F%2Fpractice.geeksforgeeks.org%2Fproblems%2Fsum-tree%2F1&v=nHMQ33LZ6oA


